# This is a basic workflow to help you get started with Actions

name: Generate Markdown API Documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    # Midnight on the first day of every month
    - cron: '0 0 1 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

    
jobs:      
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: rest-api-docs-md
      
      - uses: actions/checkout@v3
        with:
          repository: github/rest-api-description
          path: rest-api-description
          
      - uses: actions/setup-python@v4
        with: 
          python-version: '3.9'

      - name: 'Run code generation'
        run: |
          python ../.github/workflows/generate.py ../rest-api-description/descriptions/api.github.com/api.github.com.json .

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: Hubot
          commit_user_email: hubot@users.noreply.github.com
          commit_author: Hubot <hubot@users.noreply.github.com>
